apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-crowler
  namespace: open5gs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-crowler
  template:
    metadata:
      labels:
        app: core-crowler
    spec:
      nodeSelector:
        kubernetes.io/hostname: kube-mec   # force scheduling on kube-mec node
      containers:
        - name: core-crowler
          image: tatendaupc/core-crowler:latest
          imagePullPolicy: Always
          command: ["python", "-m", "core_crowler.runners.run_loc_crowler"]
          envFrom:
            - configMapRef:
                name: core-crowler-config
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
            - name: kubectl-bin
              mountPath: /usr/bin/kubectl
              readOnly: true
            - name: kube-config
              mountPath: /root/.kube
              readOnly: true
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: kubectl-bin
          hostPath:
            path: /usr/bin/kubectl
            type: File
        - name: kube-config
          hostPath:
            path: /home/generic/.kube   # replace 'generic' with the host username
            type: Directory
      restartPolicy: Always
