apiVersion: v1
kind: Service
metadata:
  name: as
  namespace: af-core
spec:
  selector:
    app: as
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: m3
      port: 7777
      targetPort: 7777
  type: ClusterIP
