apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-cmap
  labels:
    nf-type: ausf
data:
  ausf.yaml: |
    logger:
        file: /open5gs/ausf.log

    ausf:
      sbi:
      - addr: 0.0.0.0
        advertise: 10.104.149.89

    nrf:
     sbi:
      name: 10.98.124.179
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
