apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-cmap
  labels:
    nf-type: ausf
data:
  ausf.yaml: |
    logger:
        file: /open5gs/ausf.log

    ausf:
      sbi:
      - addr: 0.0.0.0
        advertise: 10.100.69.194

    nrf:
     sbi:
      name: 10.97.232.251
    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
