apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-cmap
  labels:
    nf-type: pcf
data:
  pcf.yaml: |
    logger:
        file: /open5gs/pcf.log

    db_uri: mongodb://10.97.101.228/open5gs

    pcf:
      sbi:
      - addr: 0.0.0.0
        advertise: 10.101.11.80

    nrf:
      sbi:
        name: 10.97.232.251  # Using service name
        port: 80       # Changed to match your NRF service

    sbi:
        server:
          no_tls: true
        client:
          no_tls: true

    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
