apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prometheus
  name: svcmonitor-amarisoft
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    targetPort: 80
  selector:
    matchLabels:
      amarisoft: amari-sf