{{- if .Values.ap.enabled }}

# Service for AP (Application Provider)
apiVersion: v1
kind: Service
metadata:
  name: ap-svc
  labels:
    app: ap
spec:
  type: NodePort
  selector:
    app: ap
  ports:
    - name: ui
      port: 8000
      targetPort: 8000
      nodePort: 30081

---

# Deployment for AP (Application Provider)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ap-depl
  labels:
    app: ap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ap
  template:
    metadata:
      labels:
        app: ap
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - {{ .Values.nodes.application | quote }}

      initContainers:
        - name: wait-for-as-and-af
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Waiting for AS (as-svc:80)..."
              until nc -z as-svc 80; do echo "AS not ready"; sleep 2; done
              echo "AS is ready."

              echo "Waiting for AF (af-svc:5555)..."
              until nc -z af-svc 5555; do echo "AF not ready"; sleep 2; done
              echo "AF is ready."

        - name: copy-entrypoint
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "Copying custom entrypoint to shared volume..."
              cp /config/application-provider-entrypoint.sh /shared/
              chmod +x /shared/application-provider-entrypoint.sh
          volumeMounts:
            - name: ap-config
              mountPath: /config
            - name: shared-dir
              mountPath: /shared

      containers:
        - name: ap
          image: tatendaupc/tatenda-ap:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Using custom entrypoint";
              cp /shared/application-provider-entrypoint.sh /usr/local/bin/application-provider-entrypoint.sh;
              chmod +x /usr/local/bin/application-provider-entrypoint.sh;
              exec /usr/local/bin/application-provider-entrypoint.sh
          env:
            - name: M1_PORT
              value: "5555"
            - name: RUN_MSAF_CONFIGURATION_TOOL
              value: "true"
            - name: RUN_MANAGEMENT_UI
              value: "true"
            - name: OPTIONS_ENDPOINT
              value: "http://10.96.0.188:5555/3gpp-m1/v2/provisioning-sessions/"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: ap-config
              mountPath: /etc/rt-5gms/af-sync.conf
              subPath: af-sync.conf
            - name: ap-config
              mountPath: /etc/rt-5gms/streams.json
              subPath: streams.json
            - name: shared-dir
              mountPath: /shared

      volumes:
        - name: ap-config
          configMap:
            name: ap-config
        - name: shared-dir
          persistentVolumeClaim:
            claimName: 5gms-shared-pvc
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.nodes.application }}

{{- end }}
