apiVersion: v1
kind: ConfigMap
metadata:
  name: nef-cmap
  labels:
    nf-type: nef
data:
  nef.yaml: |
    logger:
        file: /open5gs/nef.log

    nef:
      sbi:
      - addr: 0.0.0.0
        advertise: 10.108.21.84

    nrf:
      sbi:
        name: 10.107.25.39

    

    sbi:
        server:
          no_tls: true
        client:
          no_tls: true
