FROM ubuntu:focal

WORKDIR /

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
   apt-get -yq dist-upgrade && \
   apt-get --no-install-recommends -qqy install python3-pip python3-setuptools python3-wheel ninja-build build-essential flex bison git libsctp-dev libgnutls28-dev libgcrypt-dev libssl-dev libidn11-dev libmongoc-dev libbson-dev libyaml-dev libnghttp2-dev libmicrohttpd-dev libcurl4-gnutls-dev libnghttp2-dev libtins-dev libtalloc-dev meson && \
   apt-get --no-install-recommends -qqy install ufw iproute2 iptables iputils-ping tcpdump cmake curl gnupg && \
   git clone https://github.com/open5gs/open5gs --branch v2.4.0 && cd open5gs && meson build --prefix=`pwd`/install/ && ninja -C build && cd build && ninja install